version: '3.8'

services:
  pipeline:
    image: ${IMAGE}
    container_name: pipeline-test
    ports:
      - "8080:8080"
    restart: "no"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 pipeline-test
    depends_on:
      - pipeline-test